# Generated by Django 4.2.2 on 2023-06-15 11:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importance', models.CharField(choices=[('x', 'Minor'), ('X', 'Major')], default='x', max_length=1)),
            ],
        ),
        migrations.AlterModelOptions(
            name='process',
            options={'permissions': [('is_qm', 'Quality manager')], 'verbose_name': 'Process', 'verbose_name_plural': 'Processes'},
        ),
        migrations.CreateModel(
            name='PolicyAxis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, 'Draft'), (1, 'Applicable'), (2, 'Retired')], default=0)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('name', models.SlugField(max_length=4)),
                ('desc', models.CharField(max_length=64)),
                ('long_desc', models.TextField()),
                ('reviewed', models.DateField(default=django.utils.timezone.now)),
                ('processes', models.ManyToManyField(through='core.Contribution', to='core.process')),
            ],
            options={
                'verbose_name': 'Quality policy axis',
                'verbose_name_plural': 'Quality policy axes',
            },
        ),
        migrations.AddField(
            model_name='contribution',
            name='axis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.policyaxis'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.process'),
        ),
    ]
