# Generated by Django 4.2.2 on 2023-06-17 17:27

import concurrency.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contribution_alter_process_options_policyaxis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyaxis',
            name='version',
            field=concurrency.fields.AutoIncVersionField(default=0, help_text='record revision number'),
        ),
        migrations.AddField(
            model_name='process',
            name='version',
            field=concurrency.fields.AutoIncVersionField(default=0, help_text='record revision number'),
        ),
    ]
