# Generated by Django 4.2.2 on 2023-06-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_policyaxis_version_process_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contribution',
            options={'verbose_name': 'Contribution', 'verbose_name_plural': 'Contributions'},
        ),
        migrations.AddConstraint(
            model_name='policyaxis',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 1)), fields=('name',), name='policyaxis_name'),
        ),
        migrations.AddConstraint(
            model_name='policyaxis',
            constraint=models.CheckConstraint(check=models.Q(('end_date__gte', models.F('start_date')), ('end_date', None), _connector='OR'), name='policyaxis_dates'),
        ),
    ]
