# Generated by Django 4.2.2 on 2023-06-20 18:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_alter_contribution_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyaxis',
            name='processes',
            field=models.ManyToManyField(blank=True, through='core.Contribution', to='core.process'),
        ),
        migrations.AlterField(
            model_name='process',
            name='pilots',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
