# Generated by Django 4.2.2 on 2023-06-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_policyaxis_processes_alter_process_pilots'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policyaxis',
            options={'ordering': ['model_order'], 'verbose_name': 'Quality policy axis', 'verbose_name_plural': 'Quality policy axes'},
        ),
        migrations.AlterModelOptions(
            name='process',
            options={'ordering': ['model_order'], 'permissions': [('is_qm', 'Quality manager')], 'verbose_name': 'Process', 'verbose_name_plural': 'Processes'},
        ),
        migrations.AddField(
            model_name='policyaxis',
            name='model_order',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='process',
            name='model_order',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
    ]
