# Generated by Django 4.2.2 on 2023-06-30 16:06

from django.db import migrations


def reorder(apps, schema_editor):
    """Reorder Process and PolicyAxis"""
    for modelname in ('Process', 'PolicyAxis'):
        Model = apps.get_model("core", modelname)
        for order, item in enumerate(Model.objects.all(), 1):
            item.model_order = order
            item.save(update_fields=['model_order'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_policyaxis_options_alter_process_options_and_more'),
    ]

    operations = [
        migrations.RunPython(reorder, reverse_code=migrations.RunPython.noop),
    ]
