# Generated by Django 4.2.2 on 2023-07-06 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20230630_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=4)),
                ('desc', models.CharField(max_length=64)),
                ('long_desc', models.TextField()),
                ('value', models.CharField(max_length=32)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.process')),
            ],
            options={
                'verbose_name': 'Objective',
                'verbose_name_plural': 'Objectives',
            },
        ),
    ]
