# Generated by Django 4.2.2 on 2023-07-07 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_objective'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objective',
            options={'ordering': ['process__name', 'name'], 'verbose_name': 'Objective', 'verbose_name_plural': 'Objectives'},
        ),
    ]
