# Generated by Django 4.2.2 on 2023-07-08 09:41

import concurrency.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_alter_objective_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyaxis',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Draft'), (1, 'Applicable'), (2, 'Retired'), (3, 'authorized')], default=0),
        ),
        migrations.AlterField(
            model_name='process',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Draft'), (1, 'Applicable'), (2, 'Retired'), (3, 'authorized')], default=0),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, 'Draft'), (1, 'Applicable'), (2, 'Retired'), (3, 'authorized')], default=0)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('version', concurrency.fields.AutoIncVersionField(default=0, help_text='record revision number')),
                ('name', models.CharField(max_length=64)),
                ('pdf', models.FileField(upload_to='docs')),
                ('autority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('parents', models.ManyToManyField(related_name='children', to='core.document')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.process')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='process',
            name='doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='core.document'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 1)), fields=('name',), name='document_name'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(check=models.Q(('end_date__gte', models.F('start_date')), ('end_date', None), _connector='OR'), name='document_dates'),
        ),
    ]
