# Generated by Django 4.2.2 on 2023-07-08 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_policyaxis_status_alter_process_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'permissions': [('authorize_document', 'May authorize documents')]},
        ),
    ]
