# Generated by Django 4.2.2 on 2023-07-09 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_document_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='previous',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='successor', to='core.document'),
        ),
        migrations.AddField(
            model_name='policyaxis',
            name='previous',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='successor', to='core.policyaxis'),
        ),
        migrations.AddField(
            model_name='process',
            name='previous',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='successor', to='core.process'),
        ),
    ]
