# Generated by Django 4.2.2 on 2023-07-17 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_document_previous_policyaxis_previous_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ('process', 'name', '-start_date'), 'permissions': [('authorize_document', 'May authorize documents')]},
        ),
        migrations.RemoveConstraint(
            model_name='document',
            name='document_name',
        ),
        migrations.AlterField(
            model_name='document',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='children', to='core.document'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 1)), fields=('process_id', 'name'), name='document_name'),
        ),
    ]
